mod 'puppet-archive', :latest
mod 'puppet-extlib', :latest
mod 'puppet-fail2ban', :latest
mod 'puppet-firewalld', :latest
mod 'puppet-grafana', :latest
mod 'puppet-logrotate', :latest
mod 'puppet-openssl', :latest
mod 'puppet-prometheus', :latest
mod 'puppet-systemd', :latest
mod 'puppetlabs-apache', :latest
mod 'puppetlabs-apt', :latest
mod 'puppetlabs-concat', :latest
mod 'puppetlabs-stdlib', :latest
mod 'rehan-samba', :latest
mod 'saz-sudo', :latest
mod 'saz-ssh', :latest
