mod 'puppet-extlib', :latest
mod 'puppet-fail2ban', :latest
mod 'puppet-firewalld', :latest
mod 'puppet-grafana', :latest
mod 'puppet-prometheus', :latest
mod 'puppet-systemd', :latest
mod 'puppetlabs-apt', :latest
mod 'puppetlabs-stdlib', :latest
mod 'rehan-samba', :latest
mod 'saz-sudo', :latest
mod 'saz-ssh', :latest
